email = "kangkna@gmail.com"
address = "quincy"
nationality = "south korea"
age = 29
month = 8
year = 1992
amount_paid = 3500.00
amount_remaining = 1200.00
hours_remaining = 24.5
deposit_paid = true
young = true
deposit_remaining = false
